######! GET ALL WISHLISTS in DB
GET http://localhost:5050/wishlists

######! GET wishlist from a specific user for its ID
GET http://localhost:5050/users/64dd1d5a7d3d23cce7aecc6a/wishlist

######! POST new element in user's wishlist
POST http://localhost:5050/users/64f6336f1ae757a5faca6f99/wishlist/create HTTP/1.1
Content-Type: application/json

{
    "content": "Creative Desk",
    "price": 890.50
}

######! PATCH specific element in user's wishlist
PATCH http://localhost:5050/users/64f22005eccc85c888d43882/wishlist/64f9899015d11a51ea1ed043/edit HTTP/1.1
Content-Type: application/json

{
    "description" : "GET THIS KEYBOARD"
}

######! DELETE specific element in user's wishlist
DELETE http://localhost:5050/users/64f22005eccc85c888d43882/wishlist/64f9aba415d11a51ea1ed332/delete

######! DELETE all elements from user's wishlist
DELETE http://localhost:5050/users/64dd1d5a7d3d23cce7aecc6a/wishlist/clear