######! GET ALL WISHLISTS in DB
GET http://localhost:5050/wishlists

######! GET wishlist from a specific user for its ID
GET http://localhost:5050/users/64dd1d5a7d3d23cce7aecc6a/wishlist

######! POST new element in user's wishlist
POST http://localhost:5050/users/64dd1d5a7d3d23cce7aecc6a/wishlist/create HTTP/1.1
Content-Type: application/json

{
    "content": "thinkpad",
    "price": 2700.90
}

######! PATCH specific element in user's wishlist
PATCH http://localhost:5050/users/64dd1d5a7d3d23cce7aecc6a/wishlist/64f0ec903ae3640fe19d3701/edit HTTP/1.1
Content-Type: application/json

{
    "content": "Viaggio a Tokyo (edited)",
    "price": 3999.00
}

######! DELETE specific element in user's wishlist
DELETE http://localhost:5050/users/64dd1d5a7d3d23cce7aecc6a/wishlist/64f0f615b1934643cc328930/delete

######! DELETE all elements from user's wishlist
DELETE http://localhost:5050/users/64dd1d5a7d3d23cce7aecc6a/wishlist/clear